# Generated by Django 5.1.1 on 2024-09-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasafiRet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
