# Generated by Django 5.1.1 on 2024-09-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasafiRet', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=',media/images'),
        ),
    ]
