# Generated by Django 5.1.1 on 2024-09-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasafiRet', '0005_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
